### ISSUE TITLE
Subscribe Fails with +OK? (2.0.8)

### ISSUE THREAD

**Issue by SattaiLanfear** [scredis/scredis#11]
I've been getting sporradic errors on subscribing occasionally.

```scala
[error] s.i.DecoderActor - Could not decode PubSubMessage: +OK\r\n
scredis.exceptions.RedisProtocolException: Invalid PubSubResponse received: SimpleStringResponse(OK)
        at scredis.protocol.Protocol$.decodePubSubResponse(Protocol.scala:337)
        at scredis.io.DecoderActor$$anonfun$receive$1.applyOrElse(DecoderActor.scala:53)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
        at scredis.io.DecoderActor.aroundReceive(DecoderActor.scala:18)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
```

Most of the time it succeeds, just... now and then this happens...

Not sure what might help, but the subscribe attempt is made pretty early in the setup of my application, so it's possible scredis is still authenticating perhaps.

**Comment by jastice** [comment]
Thanks for the report! Currently, this project is passively maintained, meaning we will make efforts to merge new pull requests and help out with code modifications, but there's no resources to actively follow-up on bugs. If you do find out more, please share your insights :)

**Comment by SattaiLanfear** [comment]
Having done a little research, it sounds like this might be related to the issue Livestream/scredis#51 was meant to fix.  It doesn't look like that pull request ever made it in.

**Comment by jastice** [comment]
Thanks! I do intend to merge the outstanding PRs in the near future.

**Comment by jastice** [comment]
I merged the change. I won't be doing any releases before I get some testing infrastructure running, but if you could try out a build and give feedback whether it works now that would be great.

**Comment by SattaiLanfear** [comment]
@jastice I don't currently see the change, was it pushed to the repo?

**Comment by jastice** [comment]
Oops, pushed to the wrong repo. Pushed now.

**Comment by SattaiLanfear** [comment]
Sorry for the long wait, I was pulled off the project that was using this library for a while.

The patch does seem to have remedied the problem I was seeing.

**Comment by aakoshh** [comment]
We were still experiencing this issue sporadically, and when it happened it strangely halted the whole application, be it an integration test or the packaged process. What I think the reason was that there's a race condition in the `SubscriberListenerActor`: 

When we call `subscribe` that sets the `subscriptionOpt` variable immediately, from which point it will to parse everything as a subscription response in `handleData`, unlike the base `ListenerActor` which looks at its `requests` queue to figure out what the response belongs to (and skips unexpected ones). If we subscribe too soon, while the connection is still initialising, then the actor might receive something that it didn't expect and fail. In our case the "OK" we received was probably due to setting `nameOpt`, which the base `ListenerActor` sends to the server after it has connected. 

The workaround for us was to call `unsubscribe` first and wait until it the `Future` is completed before calling `subscribe`. This should indicate that the initialisation is completed, the connection is ready, and any other message that arrives before the confirmation is still handled by the base `ListenerActor`.

**Comment by kpbochenek** [comment]
@aakoshh I noticed this issue popped up when I was running unit tests for this project.

Thanks for looking into it and providing this information, I will try to dig into this as soon as possible.
